[package]
name = "pinocchio-escrow"
version = "0.1.0"
edition = "2024"

[dependencies]
pinocchio = "0.10.2"
pinocchio-log = "0.5.1"
pinocchio-pubkey = "0.3.0"
pinocchio-system = "0.5.0"
pinocchio-token = "0.5.0"
